### ISSUE TITLE
Could not find dataset

### ISSUE THREAD

**Issue by Xnsam** [afsalashyana/FakeImageDetection#2]
Hello,

Your concept seems interesting, I would like to try out it, but could not find the dataset you mentioned...Please can provide an updated link for the dataset source ?

Thank you.

**Comment by afsalashyana** [comment]
I have used CASIA 2.0 dataset for fake/tampered images.
It was downloaded from http://forensics.idealtest.org/
Unfortunately that website is currently flagged for malicious content (it could have been hacked right now). Use this at your own risk.

You can also generate your own tampered images by using GIMP with some batch image manipulation tools like this https://github.com/alessandrofrancesconi/gimp-plugin-bimp

**Comment by Xnsam** [comment]
Thank you.

I found the dataset here https://www.kaggle.com/sophatvathana/casia-dataset


for people who are looking for it .

**Comment by afsalashyana** [comment]
Thanks for posting the link.

**Comment by sourabhyadav** [comment]
Thanks for the dataset link.
