### ISSUE TITLE
Run program

### ISSUE THREAD

**Issue by LiqwdE** [afsalashyana/FakeImageDetection#3]
How do you run the program?

**Comment by afsalashyana** [comment]
Jar build is now updated in release section https://github.com/afsalashyana/FakeImageDetection/releases/
You can run the program if you have java JRE 8 installed.

java -jar 'Fake Image Detection.jar'

**Comment by pidugusundeep** [comment]
I get this `Error: Could not find or load main class com.gc.fakeimagedetection.ui.Main` error when i run the jar file

**Comment by afsalashyana** [comment]
What JRE are you using ? Are you sure you have JavaFX available in it ?
Make sure you are using JDK 8 with JavaFX.

**Comment by pidugusundeep** [comment]
I installed but how do I make sure I have everything set up properly? 🤔

**Comment by afsalashyana** [comment]
Can you give result of following command from cmd ?

`java -version`

**Comment by pidugusundeep** [comment]
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

**Comment by afsalashyana** [comment]
You probably don't have JavaFX installed.

Try using following JRE that has JavaFX.

https://www.azul.com/downloads/zulu-community/?&version=java-8-lts&os=&os=ubuntu&architecture=x86-64-bit&package=jre-fx

**Comment by rajeevsangar** [comment]
How to train neural network for different images.how to make coorect identification of fake images because it is not identifying fake images correctly
