### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by YangHan-Morningstar** [afsalashyana/FakeImageDetection#6]
Amazing Project! Could you share your dataset, I'm looking forward to this, Thanks a lot!

**Comment by romitjain** [comment]
Hey @YangHan-Morningstar, they have mentioned the source of the dataset here: https://github.com/afsalashyana/FakeImageDetection/issues/5

**Comment by Kuncheria-Kuruvilla** [comment]
@YangHan-Morningstar  Please refer to [https://www.kaggle.com/sophatvathana/casia-dataset](https://www.kaggle.com/sophatvathana/casia-dataset)
